### ISSUE TITLE
Ktor JsonFeature ClassNotFoundException

### ISSUE THREAD

**Issue by mhss1** [TelemetryDeck/KotlinSDK#13]
Hi, I added the Kotlin SDK to my app and I'm getting this exception when the app starts:
```
java.lang.NoClassDefFoundError: Failed resolution of: Lio/ktor/client/features/json/JsonFeature$Feature;
                 	at io.ktor.client.features.json.JsonFeature.<clinit>(Unknown Source:0)
                 	at com.telemetrydeck.sdk.TelemetryClient$client$1.invoke(TelemetryClient.kt:19)
                 	at com.telemetrydeck.sdk.TelemetryClient$client$1.invoke(TelemetryClient.kt:18)
                 	at io.ktor.client.HttpClientKt.HttpClient(HttpClient.kt:40)
                 	at com.telemetrydeck.sdk.TelemetryClient.<init>(TelemetryClient.kt:18)
                 	at com.telemetrydeck.sdk.TelemetryManager.send-gIAlu-s(TelemetryManager.kt:74)
                 	at com.telemetrydeck.sdk.TelemetryBroadcastTimer$start$1$1.invokeSuspend(TelemetryBroadcastTimer.kt:48)
                 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
                 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
                 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@e3b0b42, Dispatchers.IO]
                 Caused by: java.lang.ClassNotFoundException: io.ktor.client.features.json.JsonFeature$Feature
```
I think it is because `JsonFeature` was deprecated in favor of `ContentNegotation` in Ktor now.
note: I'm using Ktor 2.0.0 in my app

**Comment by nicolasvergoz** [comment]
I have the same issue. I'm using Ktor 2.3.7
