### ISSUE TITLE
IOException: Invalid argument 

### ISSUE THREAD

**Issue by P-Emmy** [TelemetryDeck/KotlinSDK#24]
We sometimes encounter this problem in our issue-tracking tool: 

```
java.io.IOException: Invalid argument
    at java.io.UnixFileSystem.createFileExclusively0(UnixFileSystem.java)
    at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:281)
    at java.io.File.createNewFile(File.java:1004)
    at com.telemetrydeck.sdk.PersistentSignalCache.saveSignals(SourceFile:60)
    at com.telemetrydeck.sdk.PersistentSignalCache.add(SourceFile:39)
    at com.telemetrydeck.sdk.TelemetryManager.queue(SourceFile:37)
    at com.telemetrydeck.sdk.TelemetryManager.queue(SourceFile:45)
    at com.telemetrydeck.sdk.TelemetryManagerSignals$DefaultImpls.queue$default(SourceFile:35)
    at com.telemetrydeck.sdk.SessionProvider.onStart(SourceFile:26)
```

**Comment by kkostov** [comment]
Hi @P-Emmy, we've released version 2.2.0 which should address this issue!

PS: If the problem continues to persist, please include additional information about the device environment, like model and OS version, so we can try to narrow down the problem.
